package AssessmentFees_FirstSemester;
import javax.swing.*;
/**
 *
 * @author johnp
 */

public class GUI_Assessment extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Assessment
     */
    public GUI_Assessment() {
        initComponents();
        
        // Button Group Sex
        ButtonGroup bgSex = new ButtonGroup();
	bgSex.add(jRadioMale);
	bgSex.add(jRadioFemale);
        
        //Button Group Type of Student
        ButtonGroup bgType = new ButtonGroup();
        bgType.add(jRadioFreshmen);
        bgType.add(jRadioTransferee);
        bgType.add(jRadioSC);
        
        // Button Group Residency
        ButtonGroup bgResidency = new ButtonGroup();
        bgResidency.add(jRadioLocal);
        bgResidency.add(jRadioForeign);
        
       
        
        // ComboBox Year Level
        jComboBoxYearLevel.addItem("Select Year Level");
        jComboBoxYearLevel.addItem("First Year");
        jComboBoxYearLevel.addItem("Second Year");
        jComboBoxYearLevel.addItem("Third Year");
        jComboBoxYearLevel.addItem("Fourth Year");
        
        // ComboBox Program
        jComboBoxProgram.addItem("--- Select Program ---");
        jComboBoxProgram.addItem("College of Arts and Sciences (CAS)");
        jComboBoxProgram.addItem("College of Business and Management (CBM)");
        jComboBoxProgram.addItem("College of Music and the Performing Arts (CMPA)");
        jComboBoxProgram.addItem("College of Nursing and Allied Health Services (CNAHS)");
        jComboBoxProgram.addItem("College of Education (CoE)");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jName = new javax.swing.JTextField();
        jLabelName1 = new javax.swing.JLabel();
        jRadioMale = new javax.swing.JRadioButton();
        jRadioFemale = new javax.swing.JRadioButton();
        j = new javax.swing.JLabel();
        jLabelYL = new javax.swing.JLabel();
        jComboBoxYearLevel = new javax.swing.JComboBox<>();
        jLabelName3 = new javax.swing.JLabel();
        jComboBoxProgram = new javax.swing.JComboBox<>();
        jLabelTypeofStudent = new javax.swing.JLabel();
        jRadioFreshmen = new javax.swing.JRadioButton();
        jRadioTransferee = new javax.swing.JRadioButton();
        jLabelName4 = new javax.swing.JLabel();
        jLabelName5 = new javax.swing.JLabel();
        jComboBoxCourse = new javax.swing.JComboBox<>();
        jRadioLocal = new javax.swing.JRadioButton();
        jLabelTypeofStudent1 = new javax.swing.JLabel();
        jRadioForeign = new javax.swing.JRadioButton();
        jUnits = new javax.swing.JTextField();
        jLabelName6 = new javax.swing.JLabel();
        jFees = new javax.swing.JTextField();
        jRadioSC = new javax.swing.JRadioButton();
        JClearButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jOutput = new javax.swing.JTextArea();
        jConfirm = new javax.swing.JButton();
        TipolLogo = new javax.swing.JLabel();
        jbackground = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("St. Paul University Manila");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 417, -1));

        jLabelName.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jLabelName.setText("Name:");
        getContentPane().add(jLabelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 54, -1));

        jName.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNameActionPerformed(evt);
            }
        });
        getContentPane().add(jName, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 122, 513, -1));

        jLabelName1.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jLabelName1.setText("Sex:");
        getContentPane().add(jLabelName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 130, 42, -1));

        jRadioMale.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jRadioMale.setText("Male");
        jRadioMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioMaleActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 130, 77, -1));

        jRadioFemale.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jRadioFemale.setText("Female");
        jRadioFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioFemaleActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 130, 77, -1));

        j.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        j.setText("St. Paul University System");
        getContentPane().add(j, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, -1, -1));

        jLabelYL.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jLabelYL.setText("Year Level:");
        getContentPane().add(jLabelYL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 78, 30));

        jComboBoxYearLevel.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jComboBoxYearLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxYearLevelActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxYearLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 164, 221, -1));

        jLabelName3.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jLabelName3.setText("Program:");
        getContentPane().add(jLabelName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 78, -1));

        jComboBoxProgram.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jComboBoxProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProgramActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxProgram, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 204, 400, -1));

        jLabelTypeofStudent.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jLabelTypeofStudent.setText("Applying as:");
        getContentPane().add(jLabelTypeofStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 100, -1));

        jRadioFreshmen.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jRadioFreshmen.setText("Freshmen");
        jRadioFreshmen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioFreshmenActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioFreshmen, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 92, -1));

        jRadioTransferee.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jRadioTransferee.setText("Transferee");
        jRadioTransferee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioTransfereeActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioTransferee, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 162, 87, -1));

        jLabelName4.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jLabelName4.setText("Desired Course of Study:");
        getContentPane().add(jLabelName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 163, -1));

        jLabelName5.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jLabelName5.setText("Units:");
        getContentPane().add(jLabelName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 52, -1));

        jComboBoxCourse.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jComboBoxCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCourseActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 200, 340, -1));

        jRadioLocal.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jRadioLocal.setText("Local");
        getContentPane().add(jRadioLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 160, 98, -1));

        jLabelTypeofStudent1.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jLabelTypeofStudent1.setText("Residency:");
        getContentPane().add(jLabelTypeofStudent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(798, 162, 99, -1));

        jRadioForeign.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jRadioForeign.setText("Foreign");
        jRadioForeign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioForeignActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioForeign, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 160, 98, -1));

        jUnits.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jUnits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUnitsActionPerformed(evt);
            }
        });
        getContentPane().add(jUnits, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 244, 159, -1));

        jLabelName6.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jLabelName6.setText("Other Fees:");
        getContentPane().add(jLabelName6, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 245, 78, -1));
        getContentPane().add(jFees, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 244, 251, -1));

        jRadioSC.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jRadioSC.setText("Second Courser");
        jRadioSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioSCActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 162, 120, -1));

        JClearButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        JClearButton.setText("Clear");
        JClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JClearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(JClearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 294, 346, 53));

        jOutput.setColumns(20);
        jOutput.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jOutput.setRows(5);
        jScrollPane1.setViewportView(jOutput);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 374, 945, 153));

        jConfirm.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jConfirm.setText("Confirm");
        jConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConfirmActionPerformed(evt);
            }
        });
        getContentPane().add(jConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(573, 294, 400, 53));

        TipolLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AssessmentFees_FirstSemester/St. Paul Logo.png"))); // NOI18N
        TipolLogo.setText("jLabel4");
        getContentPane().add(TipolLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 99, 98));

        jbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AssessmentFees_FirstSemester/St. Paul-Pao.png"))); // NOI18N
        getContentPane().add(jbackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jRadioButton1.setText("jRadioButton1");
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNameActionPerformed

    private void jRadioMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioMaleActionPerformed

    private void jRadioFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioFemaleActionPerformed

    private void jComboBoxYearLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxYearLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxYearLevelActionPerformed

    private void jComboBoxProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProgramActionPerformed
    try{
            if (jComboBoxProgram.getSelectedItem().equals("--- Select Program ---")){
            
                jComboBoxCourse.removeAllItems();
            }
        
            else if (jComboBoxProgram.getSelectedItem().equals("College of Arts and Sciences (CAS)")){
            
                jComboBoxCourse.removeAllItems();
                jComboBoxCourse.addItem("Select Your Desired Course");
                jComboBoxCourse.addItem("Bachelor of Arts in Communication");
                jComboBoxCourse.addItem("Bachelor of Arts in English Language");
                jComboBoxCourse.addItem("Bachelor of Arts in Visual Design and Communication");
                jComboBoxCourse.addItem("Bachelor of Science in Psychology");
                
            }
            
            else if (jComboBoxProgram.getSelectedItem().equals("College of Business and Management (CBM)")){

                jComboBoxCourse.removeAllItems();
                jComboBoxCourse.addItem("Select Your Desired Course");
                jComboBoxCourse.addItem("Bachelor of Science in Business Administration Major in Marketing Management");
                jComboBoxCourse.addItem("Bachelor of Science in Computer Science");
                jComboBoxCourse.addItem("Bachelor of Science in Entrepreneurship");
                jComboBoxCourse.addItem("Bachelor of Science in Hospitality Management Major in Culinary Arts");
                jComboBoxCourse.addItem("Bachelor of Science in Hospitality Management Major in Institutional Management");
                jComboBoxCourse.addItem("Bachelor of Science in Information Technology");
                jComboBoxCourse.addItem("Bachelor of Science in Science in Management Accounting");
                jComboBoxCourse.addItem("Bachelor of Science in Science in Tourism Management");
            }
            
            else if (jComboBoxProgram.getSelectedItem().equals("College of Music and the Performing Arts (CMPA)")){

                jComboBoxCourse.removeAllItems();
                jComboBoxCourse.addItem("Select Your Desired Course");
                jComboBoxCourse.addItem("Bachelor of Music in Collaborative Piano");
                jComboBoxCourse.addItem("Bachelor of Music in Guitar");
                jComboBoxCourse.addItem("Bachelor of Music in Marimba");
                jComboBoxCourse.addItem("Bachelor of Music in Music Education");
                jComboBoxCourse.addItem("Bachelor of Music in Music Education with concentration in Composition");
                jComboBoxCourse.addItem("Bachelor of Music in Music Education with concentration in Music Theory");
                jComboBoxCourse.addItem("Bachelor of Music in Music Therapy");
                jComboBoxCourse.addItem("Bachelor of Music in Performance");
                jComboBoxCourse.addItem("Bachelor of Music in Piano");
                jComboBoxCourse.addItem("Bachelor of Music in Technical Theater");
                jComboBoxCourse.addItem("Bachelor of Music in Violin");
                jComboBoxCourse.addItem("Bachelor of Music in Voice");
            }
            
            else if (jComboBoxProgram.getSelectedItem().equals("College of Nursing and Allied Health Services (CNAHS)")){
                        
                jComboBoxCourse.removeAllItems();
                jComboBoxCourse.addItem("Select Your Desired Course");
                jComboBoxCourse.addItem("Bachelor of Science in Nursing");    
                
            }
            
            else if (jComboBoxProgram.getSelectedItem().equals("College of Education (CoE)")) {
                jComboBoxCourse.removeAllItems();
                jComboBoxCourse.addItem("Select Your Desired Course");
                jComboBoxCourse.addItem("Bachelor of Early Childhood Education (with straight Masters Program)");
                jComboBoxCourse.addItem("Bachelor of Elementary Education (with straight Masters Program)");
                jComboBoxCourse.addItem("Bachelor of Secondary Education (with straight Masters program) Major in English");
                jComboBoxCourse.addItem("Bachelor of Secondary Education (with straight Masters program) Major in Mathematics");
                jComboBoxCourse.addItem("Bachelor of Secondary Education (with straight Masters program) Major in Science");
                jComboBoxCourse.addItem("Bachelor of Special Needs Education");
    }//GEN-LAST:event_jComboBoxProgramActionPerformed
                
    }
    catch (Exception e){
        System.out.print(e);
    }
    
}
    private void jRadioFreshmenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioFreshmenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioFreshmenActionPerformed

    private void jRadioTransfereeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioTransfereeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioTransfereeActionPerformed

    private void jComboBoxCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCourseActionPerformed

    private void jRadioForeignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioForeignActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioForeignActionPerformed

    private void jUnitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUnitsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUnitsActionPerformed

    private void jRadioSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioSCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioSCActionPerformed

    private void JClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JClearButtonActionPerformed
       jName.setText("");
       jUnits.setText("");
       jFees.setText("");
       jOutput.setText("");

       jComboBoxProgram.setSelectedIndex(0);
       jComboBoxYearLevel.setSelectedIndex(0);
       jComboBoxCourse.setSelectedIndex(0);
       
       jRadioMale.setSelected(false);
       jRadioFemale.setSelected(false);
       
       jName.requestFocus();

    }//GEN-LAST:event_JClearButtonActionPerformed

    private void jConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConfirmActionPerformed
        
        // Strings
        String Name;
        String Sex = "";
        String TypeofStudent = "";
        String Residency = "";
        String Year = (String) jComboBoxYearLevel.getSelectedItem();
        String Program = (String) jComboBoxProgram.getSelectedItem();
        String Course = (String) jComboBoxCourse.getSelectedItem();
        String AdditionalOtherFees;
        
        //Given Formula
        double Units;
        double TuitionPerUnit = 0;
        double TotalTuitionFees = 0;
        double MiscellaneousFees = 4054.00;
        double OtherFees = 4235.55;
        double AdditionalFees = 4138.60;
        double TotalFees = 0;
        
        Name = jName.getText();
        Units = Integer.parseInt(jUnits.getText());
        AdditionalOtherFees = jFees.getText();
        
        
        // Sex Radio Button
        if (jRadioMale.isSelected()){
            Sex = "Male";
        }
        else if (jRadioFemale.isSelected()){
            Sex = "Female";
        }
        
        // Type of Student - Radio Button
        if (jRadioFreshmen.isSelected()){
            TypeofStudent = "Freshmen";
        }
        
        else if (jRadioTransferee.isSelected()){
            TypeofStudent = "Transferee";
        }
        
        else if (jRadioSC.isSelected()){
            TypeofStudent = "Second Courser";
        }
        
        // Residency of Student - Radio Button
        if (jRadioLocal.isSelected()){
            TypeofStudent = "Local Student";
        }
        
        else if (jRadioForeign.isSelected()){
            TypeofStudent = "Foreign Student";
        }
        
        // BS Computer Science, BS Information Technonology and BS Nursing Courses are 2% Higher on tuition fees than other courses
        if ("Bachelor of Science in Computer Science".equals(Course) || 
            "Bachelor of Science in Information Technology".equals(Course) || 
            "Bachelor of Science in Nursing".equals(Course)){
            TuitionPerUnit = 1647.93;
            TotalTuitionFees = 1647.93 * Units;
        }
        else {
            TuitionPerUnit = 1614.97;
            TotalTuitionFees = 1614.97 * Units;
        }
        
        TotalFees = TotalTuitionFees + MiscellaneousFees + OtherFees + AdditionalFees;
        
        jOutput.setText("Name: " + Name); 
        jOutput.append("\nSex: " + Sex);
        jOutput.append("\nProgram: " + Program);
        jOutput.append("\nYear Level: " + Year);
        jOutput.append("\nType of Student: " + TypeofStudent);
        jOutput.append("\nCourse: " + Course);
        jOutput.append("\nUnits: " + Units);
        jOutput.append("\n");
        jOutput.append("\n");
        jOutput.append("\nTuition Fee Per Unit: " + TuitionPerUnit);
        jOutput.append("\nTotal Tuition Fees: " + TotalTuitionFees);
        jOutput.append("\nMiscellaneous Fees: " + MiscellaneousFees);
        
        if (jFees.getText().equals("")) {
            jOutput.append("\nOther Fees: " + OtherFees);
            jFees.setText("None");
            jOutput.append("\nAdditional Fees: " + AdditionalFees);
            jOutput.append("\n");
            jOutput.append("\n");
            jOutput.append("\nTOTAL ASSESSED FEES: " + String.format("%.2f", TotalFees));
        }
        
        else {
            jOutput.append("\nOther Fees: " + OtherFees + " + " + AdditionalOtherFees);
            jOutput.append("\nAdditional Fees: " + AdditionalFees);
            jOutput.append("\n");
            jOutput.append("\n");
            jOutput.append("\nTOTAL ASSESSED FEES: " + String.format("%.2f", TotalFees) + " + " +  AdditionalOtherFees);
        }
        
        jOutput.setEditable(false);
    }//GEN-LAST:event_jConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Assessment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Assessment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Assessment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Assessment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Assessment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JClearButton;
    private javax.swing.JLabel TipolLogo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel j;
    private javax.swing.JComboBox<String> jComboBoxCourse;
    private javax.swing.JComboBox<String> jComboBoxProgram;
    private javax.swing.JComboBox<String> jComboBoxYearLevel;
    private javax.swing.JButton jConfirm;
    private javax.swing.JTextField jFees;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelName1;
    private javax.swing.JLabel jLabelName3;
    private javax.swing.JLabel jLabelName4;
    private javax.swing.JLabel jLabelName5;
    private javax.swing.JLabel jLabelName6;
    private javax.swing.JLabel jLabelTypeofStudent;
    private javax.swing.JLabel jLabelTypeofStudent1;
    private javax.swing.JLabel jLabelYL;
    private javax.swing.JTextField jName;
    private javax.swing.JTextArea jOutput;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioFemale;
    private javax.swing.JRadioButton jRadioForeign;
    private javax.swing.JRadioButton jRadioFreshmen;
    private javax.swing.JRadioButton jRadioLocal;
    private javax.swing.JRadioButton jRadioMale;
    private javax.swing.JRadioButton jRadioSC;
    private javax.swing.JRadioButton jRadioTransferee;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jUnits;
    private javax.swing.JLabel jbackground;
    // End of variables declaration//GEN-END:variables
}
